### ISSUE TITLE
code

### ISSUE THREAD

**Issue by bob791** [fabiopoiesi/gedi#6]
Hello, what about the rest of the code?

**Comment by fabiopoiesi** [comment]
The rest of the code will be uploaded soon. 
In Italy is holiday period and workload may slow down a bit.
Sorry for the inconvenience.

**Comment by bob791** [comment]
Hello Professor, is it convenient to provide links to preprocessed Kitti datasets? Thanks very much！

**Comment by fabiopoiesi** [comment]
I used this dataset: https://www.cvlibs.net/datasets/kitti/eval_odometry.php

**Comment by bob791** [comment]
Hello, could you please provide the data of Figure 4 in the paper? Thank you!
